name: Linux Getter

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: r/linuxmasterrace getter
      run: node ./src/linuxmasterrace.js
      env:
        SLACK_HOOK_PATH_MEMES: ${{ secrets.SLACK_HOOK_PATH_MEMES }}
        SLACK_HOOK_PATH_PENGUINS: ${{ secrets.SLACK_HOOK_PATH_PENGUINS }}
