name: r/ProgrammerHumor

on:
  push:
    branches:
      - master
      - actions-ph
  pull_request:
    branches:
      - master
  schedule:
    - cron: "0 14 * * 1-5"
    - cron: "0 17 * * 1-5"
    - cron: "0 21 * * 1-5"

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.13
      uses: actions/setup-go@v1
      with:
        go-version: 1.13
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Get + Vendor dependencies 🏗
      run: |
        go get -v -t -d ./...
        go mod vendor

    - name: Run 🤖
      run: go run ./pkg/programmerHumor/prgmhumor.go
      env:
        SLACK_HOOK_PATH_MEMES: ${{ secrets.SLACK_HOOK_PATH_TEST }}
