name: Node CI

on:
  schedule:
    - cron: "0 14 * * 1-5"
    - cron: "0 17 * * 1-5"
    - cron: "0 21 * * 1-5"

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: r/ProgrammerHumor getter
      run: node ./src/prgmhumor.js
      env:
        SLACK_HOOK_PATH_MEMES: ${{ secrets.SLACK_HOOK_PATH_MEMES }}
        SLACK_HOOK_PATH_PENGUINS: ${{ secrets.SLACK_HOOK_PATH_PENGUINS }}
